### ISSUE TITLE
Initialization

### ISSUE THREAD

**Issue by lauwel** [luuleitner/deepMTJ#2]
Hi Cristoph! Thanks for sharing your awesome project.

I'm struggling to set up deepMTJ on my computer. In the README, there's a line that says "Create the deepMTJ virtual environment in your Anaconda terminal and install all necessary libraries (listed in the requirements.txt file) [...]". When I cloned the repository, I couldn't find the "requirements.txt" file, so I ran into an error when I ran the code through Anaconda in the deepMTJ directory (i.e. CondaFileIOError: 'requirements.txt'. [Errno 2] No such file or directory: 'requirements.txt'"). Did I miss it somewhere?

I then went to Colab and ran the sample code which worked great. I only had a problem when I went to upload my own video (which is an uncompressed AVI created in MATLAB as I'm not using a clinical-grade ultrasound machine). I tried to match the file parameters to the esaote_video.avi sample video, but it seems I may have missed something. I'm happy to share my video if that would be helpful (though I can't share it here as AVI is unsupported by Github). 

Any suggestions you have on either issue would be helpful. Thanks again for sharing!

Lauren

**Comment by luuleitner** [comment]
Dear Lauren,
thank you very much for your feedback. Indeed, the requirments.txt was missing! I uploaded the file to the repo. Let me know if you experience any further issues with your installation!

As for your video and online prediction, I can take a look (please send me a sample video to my email christoph.leitner@tugraz.at).

With kind regards
Christoph
